[2025-03-15 08:38:36 +0000] [32901] [INFO] Starting gunicorn 23.0.0
[2025-03-15 08:38:36 +0000] [32901] [INFO] Listening at: http://0.0.0.0:5000 (32901)
[2025-03-15 08:38:36 +0000] [32901] [INFO] Using worker: sync
[2025-03-15 08:38:36 +0000] [32902] [INFO] Booting worker with pid: 32902
[2025-03-15 08:38:36 +0000] [32903] [INFO] Booting worker with pid: 32903
[2025-03-15 08:38:36 +0000] [32904] [INFO] Booting worker with pid: 32904
[2025-03-15 08:38:36 +0000] [32905] [INFO] Booting worker with pid: 32905
[2025-03-15 08:54:06,447] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/ec2-user/Cep-AI/app.py", line 59, in index
    return render_template('index.html', predicted_cgpa=None, error=None)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ec2-user/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[2025-03-15 08:57:57 +0000] [32903] [INFO] Worker exiting (pid: 32903)
[2025-03-15 08:57:57 +0000] [32902] [INFO] Worker exiting (pid: 32902)
[2025-03-15 08:57:57 +0000] [32905] [INFO] Worker exiting (pid: 32905)
[2025-03-15 08:57:57 +0000] [32904] [INFO] Worker exiting (pid: 32904)
[2025-03-15 08:57:57 +0000] [32901] [INFO] Handling signal: term
[2025-03-15 08:57:57 +0000] [32901] [ERROR] Worker (pid:32903) was sent SIGTERM!
[2025-03-15 08:57:57 +0000] [32901] [ERROR] Worker (pid:32904) was sent SIGTERM!
[2025-03-15 08:57:57 +0000] [32901] [ERROR] Worker (pid:32905) was sent SIGTERM!
[2025-03-15 08:57:57 +0000] [32901] [ERROR] Worker (pid:32902) was sent SIGTERM!
[2025-03-15 08:57:57 +0000] [32901] [INFO] Shutting down: Master
